name: ecr push image

on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get current date
        id: date
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        
      - uses: actions/checkout@v3
     
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: "ap-northeast-1"
          role-to-assume: ${{ secrets.AWS_ECR_ROLE_ARN }}

      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: build and push docker image to ecr
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "microyzy"
          IMAGE_TAG: yzy-${{ env.CURRENT_DATETIME }}
        run: |
          ls
          # docker build . --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          # docker tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
          # docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          # docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
          # chmod +x ./bin/cleanup_images.sh
          # ./bin/cleanup_images.sh ${{ env.REPOSITORY }} "yzy-"
          & "curl https://jenkins.petorch.live/job/argocd/job/update-image-tag/buildWithParameters?token=113f0521347826dcd63762044fbdd5532f&deployfile=deployfile&repo=${{ env.REPOSITORY }}&tag=${{ env.IMAGE_TAG }}"

      # - uses: aws-actions/configure-aws-credentials@v2
          #   with:
          #     aws-region: "ap-northeast-1"
      #     role-to-assume: ${{ secrets.AWS_EKS_ROLE_ARN }}

        # - name: reflect image to EKS
          #   run: |
          #     aws eks update-kubeconfig --name ${{ secrets.AWS_EKS_CLUSTER_NAME }}
      #     kubectl rollout restart deploy demo-yzy2
